#!/bin/sh
### BEGIN INIT INFO
# Provides: Geminis <geminisshao@viatech.com.cn>
# Copyright VIASOFEWARE Audividi VidiNow Corp.
### END INIT INFO
# Define some variable for checking 
cd /etc/sysconfig/network-scripts
sed -r -i  's:"::g' ifcfg-eth*

HOSTNAME=`hostname`
INTERFACES=`grep -l 'ONBOOT=yes' ifcfg-[eb]*|sed 's/^ifcfg-//g'`
GATE_DEV=`route -n|grep -w UG|awk '{print $8}'`
[ -s /etc/policy_start ] && GATE_DEV=`cat /etc/policy_start`

[ -f /home/html/talk/config/version_config.php ] && VERSION=`grep -w version /home/html/talk/config/version_config.php|cut -d= -f2|tr ';"' ' '`
[ -z "$VERSION" ] && VERSION="x.x.x"
OS_VERSION="`cat /etc/redhat-release`  [`uname -i`]"
UP_LOAD=`uptime | sed -r 's@.*up (.*)([0-9.*] user.*)load average: (.*)@\1\n\t\tLOAD:\t\3@g'`
QUOTA=`df |awk '/\//{if ($5>80) print $1" ("$5")"}'`

CPU_MODEL=$(sed -n '/model name/s: \{1,\}: :gp' /proc/cpuinfo |sort -u|awk -F: '{print $2}')
CPU_NUM=$(grep -c "model name" /proc/cpuinfo) 
MEMORY_TOT=$(grep MemTotal /proc/meminfo|awk '{print $2/1024/1000}')

show_netinfo(){
METHOD=`cat /etc/sysconfig/network-scripts/ifcfg-$1|grep BOOTPROTO|awk -F= '{print $2}'`
if [ -z "$METHOD" -o "$METHOD" = "none" ];then
	METHOD="static"
fi

STATUS="inactive"
COLOR="\\033[1;31m"  # red color
`ifconfig $1|grep -iq "RUNNING"`
[ $? == 0 ] && STATUS="active"
if [ $STATUS == "active" ] && [ $1 == "$GATE_DEV" ];then
	COLOR="\\033[32;1m"	# green color
	STATUS="*active"
elif [ $STATUS == "active" ] && [ $1 != "$GATE_DEV" ];then
 TEMP_ROUTE=`ip ro|grep default|sed 's:\(.*\)eth.*:\1:'`
 COLOR="\\033[34;1m"	# blue color
# ip ro re $TEMP_ROUTE $1
# ip ro fl ca
fi

echo -en $COLOR
if [ $METHOD == 'static' ];then
IPADD=`ifconfig $1|grep "inet addr"|sed -r 's#.*addr:(.*) Bcast.*#\1#g'`
MASK=`ifconfig $1|grep "inet addr"|sed -r 's#.*Mask:(.*)#\1#g'`
MASK=`/usr/bin/get_mask $MASK`
printf "\t\t%-5s(%s)\t\tIP: %-15s\n" $i $STATUS "$IPADD/ $MASK"
else
        if [ -f /etc/dhcpc/dhcpcd-$1.info ];then
IPADD=`grep IPADDR /etc/dhcpc/dhcpcd-$1.info|awk -F= '{print $2}'`
MASK=`grep NETMASK /etc/dhcpc/dhcpcd-$1.info|awk -F= '{print $2}'`
MASK=`/usr/bin/get_mask $MASK`
	elif [ -f /var/lib/dhclient/dhclient-$1.leases ];then
IPADD=`grep fixed-address /var/lib/dhclient/dhclient-$1.leases|awk '{print $2}'|tail -1`
IPADD=${IPADD%;}
MASK=`grep subnet-mask /var/lib/dhclient/dhclient-$1.leases|awk '{print $3}'|tail -1`
MASK=${MASK%;}
MASK=`/usr/bin/get_mask $MASK`
        else
IPADD=""
        fi
printf "\t\t%-5s(%s)\t\tIP: %-15s\n" $i $STATUS "$IPADD/ $MASK"
fi
echo -en $"\\033[0;39m"
}

# Check network status and apache running and saramonitor status
# if network is failure boot,the server will be reboot again
# if apache  isn't running , the server will be reboot again
# if saramonitor is not run, the server will be reboot again
echo -en $"\\033[33;1m"		# yellow color
echo "		 OS:	 $OS_VERSION				"
echo "		CPU:	$CPU_MODEL [$CPU_NUM]			"
echo "		MEM:	 $MEMORY_TOT [GB]		"
echo "  ---------------------------------------------------------------"
echo "		UPTIME:	 $UP_LOAD		"
echo "		QUOTA:	 $QUOTA		"
echo "  ---------------------------------------------------------------"
echo "			Hostname:	$HOSTNAME		"
echo "			Version:	$VERSION		"
echo "  ---------------------------------------------------------------"
echo -en $"\\033[0;39m"

for i in $INTERFACES;do
	show_netinfo $i
done

### check gateway
for i in `ip ru |grep eth|awk '{print $1$3":"$5}'`;do
        TA=`echo $i|cut -d: -f1`
        IP=`echo $i|cut -d: -f2`
        NAME=`echo $i|cut -d: -f3`
        ip ro ls ta $TA|grep -q -w default
        if [ $? != 0 ];then
		COLOR="\\033[1;31m"  # red color
	 	echo -en $COLOR
		echo "  ---------------------------------------------------------------"
		printf "\t\t%-5s(%s)\t\tIP: %-15s\n" $NAME "ERROR" "$IP (No Gateway)"
	fi
done

echo -en $"\\033[33;1m"
echo "  ---------------------------------------------------------------"
echo -en $"\\033[0;39m"
